### ISSUE TITLE
Issue on MacBook Pro

### ISSUE THREAD

**Issue by hafiz-mohsin-confiz** [iccthedral/ipa2diawi#1]
I have installed 'ipa2diawi' using following command on Mac Pro
  npm i ipa2diawi -g
 when i run the command below
 ipa2diawi /Users/Dropbox/Test.ipa
 i received the following error on Terminal
 [SyntaxError: Unexpected token <]
 how to resolved the error?

**Comment by deanWombourne** [comment]
I'm also getting this error when running inside a script in bitrise. My stack looks like:

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Uploader.<anonymous> (/usr/local/lib/node_modules/ipa2diawi/ipa2diawi.js:84:33)
    at Request.self.callback (/usr/local/lib/node_modules/ipa2diawi/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/ipa2diawi/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ipa2diawi/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

**Comment by deanWombourne** [comment]
@hafiz-mohsin-confiz Hi, I couldn't get this to work either, and no-one has replied to your comment since 31 Jul so I've written an alternative module here: https://github.com/deanWombourne/node-diawi

**Comment by hafiz-mohsin-confiz** [comment]
How can work this script on MacBook previous script was written in Python and now its java script?

Can you mentioned the steps to configure it on MacBook?

Waiting for you positive response...

________________________________

**Comment by deanWombourne** [comment]
The previous script is also Javascript? 

To run this on my mac I do

To Install npm, I used home-brew. You've probably already done this, because ipa2diawi is already a node module.
```
> brew install node
> brew install npm
```

To run it I would do this:
```
> npm install diawi
> diawi upload <token> <filename>
```

**Comment by hafiz-mohsin-confiz** [comment]
To run it I would do this:

> npm install diawi

After running the above command

├─┬ diawi@0.2.0




│ └─┬ request@2.83.0




│   └─┬ http-signature@1.2.0




│     ├── assert-plus@1.0.0




│     ├─┬ jsprim@1.4.1




│     │ ├── assert-plus@1.0.0




│     │ ├── extsprintf@1.3.0




│     │ └─┬ verror@1.10.0




│     │   ├── assert-plus@1.0.0




│     │   └── core-util-is@1.0.2




│     └─┬ sshpk@1.13.1




│       ├── assert-plus@1.0.0




│       ├─┬ dashdash@1.14.1




│       │ └── assert-plus@1.0.0




│       └─┬ getpass@0.1.7




│         └── assert-plus@1.0.0




└── ipa2diawi@0.0.6








npm WARN enoent ENOENT: no such file or directory, open '/Users/confiz/package.json'




npm WARN confiz No description




npm WARN confiz No repository field.




npm WARN confiz No README data




npm WARN confiz No license field.

After the above command completion then I run the diawi as a command on terminal then it cannot found the diawi as a command

MacBook-Pro-4:~ confiz$ diawi

-bash: diawi: command not found


Regards,

Mohsin Yaseen
SSE | Confiz Limited
[confiz]<http://www.confiz.com> (m) 322-559-5563 • IM (Skype) hafiz.mohsin.confiz
Leeds Centre, Gulberg III | Lahore, Pakistan

________________________________

**Comment by deanWombourne** [comment]
Oh, sorry, that's my fault - `npm install diawi` installs it locally (in ./node_modules) - but that's doesn't give you the command line version. Try `npm install -g diawi` instead - that installs it globally so you should get the diawi executable as well :)

**Comment by hafiz-mohsin-confiz** [comment]
Thanks 😉 Now its work as expected.


Regards,

Mohsin Yaseen
SSE | Confiz Limited
[confiz]<http://www.confiz.com> (m) 322-559-5563 • IM (Skype) hafiz.mohsin.confiz
Leeds Centre, Gulberg III | Lahore, Pakistan

________________________________

**Comment by deanWombourne** [comment]
Glad I could help :)
